import Head from 'next/head';
import React, { useState } from 'react';
import Image from 'next/image';
import BasicMenu from '../components/BasicMenu';
import { NetflixLogo } from '../components/icon';
import Link from 'next/link';
import { ChevronDownIcon } from '@heroicons/react/24/outline';

function Account() {
    const [open, setOpen] = useState(false);

    const handleClick = () => {
        setOpen(!open);
    };

    return (
        <div>
            <Head>
                <title>Cài đặt tài khoản - NetflixClone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/nficon2016.ico" />
            </Head>
            {/* Header */}
            <header className="bg-[#141414] h-14 px-2 md:h-20 md:px-11">
                <Link href="/" className="relative">
                    <NetflixLogo height="3.5rem" width="8rem" />
                </Link>

                <div className="flex items-center space-x-4 text-sm font-light">
                    <BasicMenu>
                        <div className="relative w-14 h-14 md:w-8 md:h-8 cursor-pointer">
                            <Image
                                src="https://upload.wikimedia.org/wikipedia/commons/0/0b/Netflix-avatar.png"
                                alt="Avatar"
                                fill
                                sizes="large"
                                className="rounded"
                            />
                        </div>
                    </BasicMenu>
                </div>
            </header>

            <main className="mt-20 mx-7 md:max-w-5xl md:mx-auto">
                <div className="space-y-4 mb-2 md:mb-5 md:flex md:items-center">
                    <h1 className="text-4xl">Tài khoản</h1>

                    <div className="ml-5 flex items-center space-x-2">
                        <div className="w-7 h-7 bg-[url('https://assets.nflxext.com/ffe/siteui/account/svg/membersince.svg')] bg-center" />
                        <span>Thành viên từ tháng mười một 2021</span>
                    </div>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">
                            TƯ CÁCH THÀNH VIÊN VÀ TÍNH PHÍ
                        </h2>
                        <button className="pageBtn min-w-[200px] shadow-sm">
                            Hủy tư cách thành viên
                        </button>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    lekhanh240895@gmail.com
                                </div>
                                <Link
                                    href="email"
                                    className="accountSectionLink"
                                >
                                    Thay đổi email
                                </Link>
                            </div>
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    <span className="text-[#737373]">
                                        Mật khẩu: **********
                                    </span>
                                </div>
                                <Link
                                    href="password"
                                    className="accountSectionLink"
                                >
                                    Thay đổi mật khẩu
                                </Link>
                            </div>
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    Số điện thoại: 0935737395
                                </div>
                                <Link
                                    href="/phonenumber"
                                    className="accountSectionLink"
                                >
                                    Thay đổi số điện thoại
                                </Link>
                            </div>
                        </div>
                        <div className="accountSubSection pt-3 pb-5">
                            <h2 className="text-base font-medium">
                                Không có thông tin thanh toán
                            </h2>
                        </div>
                    </section>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">
                            THÔNG TIN GÓI DỊCH VỤ
                        </h2>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">Free</div>

                                <button className="pageBtn bg-primary hover:bg-[#f40612] text-white min-w-[98px] rounded-none">
                                    Nâng cấp
                                </button>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">
                            BẢO MẬT & QUYỀN RIÊNG TƯ
                        </h2>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem items-start">
                                <div className="accountSectionInfo">
                                    Kiểm soát quyền truy cập vào tài khoản này,
                                    xem các thiết bị hoạt động gần đây nhất và
                                    hơn thế nữa.
                                </div>

                                <div className="shrink-[0.3] md:flex-shrink-0 flex flex-col items-end space-y-2 ml-2">
                                    <div>
                                        <span className="bg-[#0f84fa] p-1 text-sm rounded mr-2">
                                            Mới
                                        </span>
                                        <Link
                                            href="/phonenumber"
                                            className="accountSectionLink"
                                        >
                                            Quản lý quyền truy cập và thiết bị
                                        </Link>
                                    </div>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink"
                                    >
                                        Đăng xuất khỏi tất cả các thiết bị
                                    </Link>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink"
                                    >
                                        Tải xuống thông tin cá nhân của bạn
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">
                            HỒ SƠ VÀ TÍNH NĂNG KIỂM SOÁT CỦA CHA MẸ
                        </h2>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    <div className="relative w-16 h-16 cursor-pointer rounded">
                                        <Image
                                            src="https://upload.wikimedia.org/wikipedia/commons/0/0b/Netflix-avatar.png"
                                            alt="Avatar"
                                            fill
                                            sizes="large"
                                        />
                                    </div>
                                    <div className="">
                                        <h3 className="text-base font-medium">
                                            Thành viên Netflix
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            Mọi độ tuổi
                                        </span>
                                    </div>
                                </div>

                                <span onClick={handleClick}>
                                    <ChevronDownIcon
                                        className="w-6 h-6 transition-all 200ms cursor-pointer"
                                        color="white"
                                        style={{
                                            transform: open
                                                ? 'rotateZ(180deg)'
                                                : 'none',
                                        }}
                                    />
                                </span>
                            </div>
                        </div>

                        <div
                            className={`${
                                open && 'hidden'
                            } space-y-5 divide-y divide-gray-700 pl-28`}
                        >
                            <div className="pt-4">
                                <div className="accountSectionItem">
                                    <div className="">
                                        <h3 className="text-base font-normal">
                                            Ngôn ngữ
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            Tiếng Việt
                                        </span>
                                    </div>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink text-sm"
                                    >
                                        Thay đổi
                                    </Link>
                                </div>
                            </div>
                            <div className="pt-4">
                                <div className="accountSectionItem">
                                    <div className="">
                                        <h3 className="text-base font-normal">
                                            Ngôn ngữ
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            Tiếng Việt
                                        </span>
                                    </div>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink text-sm"
                                    >
                                        Thay đổi
                                    </Link>
                                </div>
                            </div>
                            <div className="pt-4">
                                <div className="accountSectionItem">
                                    <div className="">
                                        <h3 className="text-base font-normal">
                                            Giới hạn xem
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            Không giới hạn.
                                        </span>
                                    </div>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink text-sm"
                                    >
                                        Thay đổi
                                    </Link>
                                </div>
                            </div>
                        </div>

                        <div className="accountSubSection pt-4">
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    <div className="relative w-16 h-16 cursor-pointer rounded">
                                        <Image
                                            src="https://occ-0-395-58.1.nflxso.net/dnm/api/v6/K6hjPJd6cR6FpVELC5Pd6ovHRSk/AAAABd-zRyXt4X3giGFwUe7qTBje-Oy0aZBYnKki5vcWzgm0QKx2sCWU3pvizcNsi6LQjZSbMpMmHScVNw8MNGoBzELgjzCrnPg.png?r=df6"
                                            alt=""
                                            fill
                                            sizes="large"
                                        />
                                    </div>
                                    <div className="">
                                        <h3 className="text-base font-medium">
                                            Trẻ em
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            7+ trờ xuống
                                        </span>
                                    </div>
                                </div>

                                <span onClick={handleClick}>
                                    <ChevronDownIcon
                                        className="w-6 h-6 transition-all 200ms cursor-pointer"
                                        color="white"
                                        style={{
                                            transform: open
                                                ? 'rotateZ(180deg)'
                                                : 'none',
                                        }}
                                    />
                                </span>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">CÀI ĐẶT</h2>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem">
                                <div className="shrink-[0.3] md:flex-shrink-0 flex flex-col space-y-2 ml-2">
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink"
                                    >
                                        Tham gia thử nghiệm
                                    </Link>

                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink"
                                    >
                                        Quản lý thiết bị tải xuống
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </main>
        </div>
    );
}

export default Account;
