import Head from 'next/head';
import React, { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ChevronDownIcon } from '@heroicons/react/24/outline';
import axios from 'axios';
import { useRouter } from 'next/router';
import useSWR, { Fetcher } from 'swr';
import Stripe from 'stripe';
import { NextApiRequest, NextApiResponse } from 'next';
import getUser from '../lib/getUser';
import { format, fromUnixTime } from 'date-fns';
import { vi } from 'date-fns/locale';

import BasicMenu from '../components/BasicMenu';
import { NetflixLogo } from '../components/icon';
import { IUser, Plan } from '../typings';

interface Props {
    plan: Plan;
}

function Account({ plan }: Props) {
    const [open1, setOpen1] = useState(false);
    const [open2, setOpen2] = useState(false);

    const formatDate = (timestamp: number) =>
        format(fromUnixTime(timestamp), 'MMMM yyyy', {
            locale: vi,
        });

    const fetcher: Fetcher<IUser, string> = (path) =>
        fetch(path).then((res) => res.json());

    const { data: user, error } = useSWR<IUser, Error>(
        '/api/users/getMe',
        fetcher,
    );

    const handleClick1 = () => {
        setOpen1(!open1);
    };

    const handleClick2 = () => {
        setOpen2(!open2);
    };

    const router = useRouter();

    const loadBillingPortal = async () => {
        const { data } = await axios.get('/api/create-portal-session');
        router.push(data.url);
    };

    if (!user) return;

    return (
        <div>
            <Head>
                <title>Cài đặt tài khoản - Netflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/nficon2016.ico" />
            </Head>

            {/* Header */}
            <header className="bg-[#141414] h-14 px-2 md:h-20 md:px-11">
                <Link href="/" className="relative">
                    <NetflixLogo height="3.5rem" width="8rem" />
                </Link>

                <div className="flex items-center space-x-4 text-sm font-light">
                    <BasicMenu>
                        <div className="relative w-14 h-14 md:w-8 md:h-8 cursor-pointer">
                            <Image
                                src="https://upload.wikimedia.org/wikipedia/commons/0/0b/Netflix-avatar.png"
                                alt="Avatar"
                                fill
                                sizes="large"
                                className="rounded"
                            />
                        </div>
                    </BasicMenu>
                </div>
            </header>

            <main className="mt-14 md:mt-20 mx-7 py-2 md:max-w-5xl md:mx-auto">
                <div className="space-y-4 mb-2 md:mb-5 md:flex md:items-center">
                    <h1 className="text-4xl">Tài khoản</h1>

                    <div className="ml-5 flex items-center space-x-2">
                        <div className="w-7 h-7 bg-[url('https://assets.nflxext.com/ffe/siteui/account/svg/membersince.svg')] bg-center" />

                        {plan.startDate && (
                            <span>
                                Thành viên từ {formatDate(plan.startDate)}
                            </span>
                        )}
                    </div>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">
                            TƯ CÁCH THÀNH VIÊN VÀ TÍNH PHÍ
                        </h2>
                        <button
                            className="pageBtn min-w-[200px] shadow-sm"
                            onClick={loadBillingPortal}
                        >
                            Hủy tư cách thành viên
                        </button>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    {user.email}
                                </div>
                                <Link
                                    href="email"
                                    className="accountSectionLink"
                                >
                                    Thay đổi email
                                </Link>
                            </div>
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    <span className="text-[#737373]">
                                        Mật khẩu: **********
                                    </span>
                                </div>
                                <Link
                                    href="password"
                                    className="accountSectionLink"
                                >
                                    Thay đổi mật khẩu
                                </Link>
                            </div>
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    Số điện thoại: 0935737395
                                </div>
                                <Link
                                    href="/phonenumber"
                                    className="accountSectionLink"
                                >
                                    Thay đổi số điện thoại
                                </Link>
                            </div>
                        </div>
                        <div className="accountSubSection pt-3 pb-5">
                            {plan.paymentMethods?.length! <= 0 ? (
                                <h2 className="text-base font-medium">
                                    Không có thông tin thanh toán
                                </h2>
                            ) : (
                                plan.paymentMethods!.map((pm) => (
                                    <div
                                        key={pm.id}
                                        className="accountSectionItem items-start"
                                    >
                                        <div className="accountSectionInfo">
                                            <h2 className="flex items-center">
                                                {pm.card?.brand.toUpperCase()}:
                                                <span className="ml-3 tracking-widest">
                                                    ******{pm.card?.last4}
                                                </span>
                                            </h2>
                                        </div>

                                        <div className="flex flex-col items-end space-y-2 ml-2">
                                            <span
                                                className="accountSectionLink cursor-pointer"
                                                onClick={loadBillingPortal}
                                            >
                                                Quản lý thông tin thanh toán
                                            </span>
                                            <span
                                                className="accountSectionLink cursor-pointer"
                                                onClick={loadBillingPortal}
                                            >
                                                Chi tiết thanh toán
                                            </span>
                                            <span
                                                className="accountSectionLink cursor-pointer"
                                                onClick={loadBillingPortal}
                                            >
                                                Thay đổi thanh toán
                                            </span>
                                        </div>
                                    </div>
                                ))
                            )}
                        </div>
                    </section>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">
                            THÔNG TIN GÓI DỊCH VỤ
                        </h2>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    {plan.name}
                                </div>

                                <button
                                    className="pageBtn bg-primary hover:bg-[#f40612] text-white min-w-[98px] rounded-none"
                                    onClick={loadBillingPortal}
                                >
                                    Nâng cấp
                                </button>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">
                            BẢO MẬT & QUYỀN RIÊNG TƯ
                        </h2>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem items-start">
                                <div className="accountSectionInfo">
                                    Kiểm soát quyền truy cập vào tài khoản này,
                                    xem các thiết bị hoạt động gần đây nhất và
                                    hơn thế nữa.
                                </div>

                                <div className="shrink-[0.5] md:flex-shrink-0 flex flex-col items-end space-y-2 ml-2">
                                    <div className="text-right">
                                        <span className="bg-[#0f84fa] p-1 text-sm rounded mr-2">
                                            Mới
                                        </span>
                                        <Link
                                            href="/phonenumber"
                                            className="accountSectionLink"
                                        >
                                            Quản lý quyền truy cập và thiết bị
                                        </Link>
                                    </div>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink"
                                    >
                                        Đăng xuất khỏi tất cả các thiết bị
                                    </Link>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink"
                                    >
                                        Tải xuống thông tin cá nhân của bạn
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">
                            HỒ SƠ VÀ TÍNH NĂNG KIỂM SOÁT CỦA CHA MẸ
                        </h2>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    <div className="relative w-16 h-16 cursor-pointer rounded">
                                        <Image
                                            src="https://upload.wikimedia.org/wikipedia/commons/0/0b/Netflix-avatar.png"
                                            alt="Avatar"
                                            fill
                                            sizes="large"
                                        />
                                    </div>
                                    <div className="">
                                        <h3 className="text-base font-medium">
                                            Thành viên Netflix
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            Mọi độ tuổi
                                        </span>
                                    </div>
                                </div>

                                <span onClick={handleClick1}>
                                    <ChevronDownIcon
                                        className="w-6 h-6 transition-all 200ms cursor-pointer"
                                        color="white"
                                        style={{
                                            transform: open1
                                                ? 'rotateZ(180deg)'
                                                : 'none',
                                        }}
                                    />
                                </span>
                            </div>
                        </div>

                        <div
                            className={`${
                                open1 && 'hidden'
                            } space-y-5 divide-y divide-gray-700 pl-28`}
                        >
                            <div className="pt-4">
                                <div className="accountSectionItem">
                                    <div className="">
                                        <h3 className="text-base font-normal">
                                            Ngôn ngữ
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            Tiếng Việt
                                        </span>
                                    </div>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink text-sm"
                                    >
                                        Thay đổi
                                    </Link>
                                </div>
                            </div>
                            <div className="pt-4">
                                <div className="accountSectionItem">
                                    <div className="">
                                        <h3 className="text-base font-normal">
                                            Ngôn ngữ
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            Tiếng Việt
                                        </span>
                                    </div>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink text-sm"
                                    >
                                        Thay đổi
                                    </Link>
                                </div>
                            </div>
                            <div className="pt-4">
                                <div className="accountSectionItem">
                                    <div className="">
                                        <h3 className="text-base font-normal">
                                            Giới hạn xem
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            Không giới hạn.
                                        </span>
                                    </div>
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink text-sm"
                                    >
                                        Thay đổi
                                    </Link>
                                </div>
                            </div>
                        </div>

                        <div className="accountSubSection pt-4">
                            <div className="accountSectionItem">
                                <div className="accountSectionInfo">
                                    <div className="relative w-16 h-16 cursor-pointer rounded">
                                        <Image
                                            src="https://occ-0-395-58.1.nflxso.net/dnm/api/v6/K6hjPJd6cR6FpVELC5Pd6ovHRSk/AAAABd-zRyXt4X3giGFwUe7qTBje-Oy0aZBYnKki5vcWzgm0QKx2sCWU3pvizcNsi6LQjZSbMpMmHScVNw8MNGoBzELgjzCrnPg.png?r=df6"
                                            alt=""
                                            fill
                                            sizes="large"
                                        />
                                    </div>
                                    <div className="">
                                        <h3 className="text-base font-medium">
                                            Trẻ em
                                        </h3>
                                        <span className="text-gray-500 text-sm">
                                            7+ trờ xuống
                                        </span>
                                    </div>
                                </div>

                                <span onClick={handleClick2}>
                                    <ChevronDownIcon
                                        className="w-6 h-6 transition-all 200ms cursor-pointer"
                                        color="white"
                                        style={{
                                            transform: open2
                                                ? 'rotateZ(180deg)'
                                                : 'none',
                                        }}
                                    />
                                </span>
                            </div>

                            <div
                                className={`${
                                    open2 && 'hidden'
                                } space-y-5 divide-y divide-gray-700 pl-28`}
                            >
                                <div className="pt-4">
                                    <div className="accountSectionItem">
                                        <div className="">
                                            <h3 className="text-base font-normal">
                                                Ngôn ngữ
                                            </h3>
                                            <span className="text-gray-500 text-sm">
                                                Tiếng Việt
                                            </span>
                                        </div>
                                        <Link
                                            href="/phonenumber"
                                            className="accountSectionLink text-sm"
                                        >
                                            Thay đổi
                                        </Link>
                                    </div>
                                </div>
                                <div className="pt-4">
                                    <div className="accountSectionItem">
                                        <div className="">
                                            <h3 className="text-base font-normal">
                                                Ngôn ngữ
                                            </h3>
                                            <span className="text-gray-500 text-sm">
                                                Tiếng Việt
                                            </span>
                                        </div>
                                        <Link
                                            href="/phonenumber"
                                            className="accountSectionLink text-sm"
                                        >
                                            Thay đổi
                                        </Link>
                                    </div>
                                </div>
                                <div className="pt-4">
                                    <div className="accountSectionItem">
                                        <div className="">
                                            <h3 className="text-base font-normal">
                                                Giới hạn xem
                                            </h3>
                                            <span className="text-gray-500 text-sm">
                                                Không giới hạn.
                                            </span>
                                        </div>
                                        <Link
                                            href="/phonenumber"
                                            className="accountSectionLink text-sm"
                                        >
                                            Thay đổi
                                        </Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="accountSection">
                    <div className="accountSectionHeader">
                        <h2 className="accountSectionHeading">CÀI ĐẶT</h2>
                    </div>

                    <section className="accountSectionContent">
                        <div className="accountSubSection">
                            <div className="accountSectionItem">
                                <div className="shrink-[0.3] md:flex-shrink-0 flex flex-col space-y-2 ml-2">
                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink text-left"
                                    >
                                        Tham gia thử nghiệm
                                    </Link>

                                    <Link
                                        href="/phonenumber"
                                        className="accountSectionLink text-left"
                                    >
                                        Quản lý thiết bị tải xuống
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </main>
        </div>
    );
}

export default Account;

interface IObject extends Stripe.Subscription {
    plan?: Stripe.Plan;
}

export const getServerSideProps = async ({
    req,
    res,
}: {
    req: NextApiRequest;
    res: NextApiResponse;
}) => {
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
        // https://github.com/stripe/stripe-node#configuration
        apiVersion: '2022-11-15',
    });

    const user = await getUser(req, res);
    const { data: subscriptions } = await stripe.subscriptions.list();

    let plan: Partial<Plan> = {};

    const userSub: IObject | undefined = subscriptions.find(
        (sub) => sub.customer === user?.stripe_customer,
    );

    const { data: paymentMethods } = await stripe.customers.listPaymentMethods(
        user?.stripe_customer as string,
        {
            type: 'card',
        },
    );

    if (userSub) {
        const price = await stripe.prices.retrieve(userSub.plan?.id || '');
        const product: Stripe.Product = await stripe.products.retrieve(
            price.product as string,
        );

        plan.name = product.name;
        plan.price = price.unit_amount!;
        plan.interval = userSub.plan?.interval;
        plan.startDate = userSub.start_date;
        plan.paymentMethods = paymentMethods;

        return {
            props: {
                plan,
            },
        };
    }

    return {
        redirect: {
            destination: '/planform',
            permanent: false,
        },
    };
};
