import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

function Login() {
    return (
        <div className='relative flex w-screen h-screen flex-col bg-black md:items-center md:justify-center md:bg-transparent'>
            <Head>
                <title>Netflix</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Image src="/../public/Netflix-background.jpg" alt="background" fill className='-z-10 !hidden opacity-60 sm:!inline' />

            <Image src="/../public/Netflix-Brand-Logo.png" alt="Logo" width={200} height={30} className='absolute left-0 -top-6  object-contain md:left-4 md:top-4' />

            <form className='relative mt-12 space-y-8 px-6 py-10 md:mt-0 md:max-w-md md:px-14 bg-black/75'>
                <h1 className='text-3xl font-semibold'>Sign In</h1>
                <div className="space-y-4">
                    <label className='inline-block w-full'><input placeholder='Email or phone number' type="email" className="input" /></label>
                    <label className='inline-block w-full'><input placeholder='Password' type="password" className='input' /></label>
                </div>
                <button type="submit" className='w-full rounded bg-[#e50914] py-3 font-semibold'>Sign In</button>

                <div className='text-[gray] space-x-2'>
                    <span>New to Netflix?</span>
                    <Link href="/signup" className='text-white hover:underline'>Sign up now</Link>
                </div>
            </form>
        </div>
    )
}

export default Login