import { CheckIcon } from '@heroicons/react/24/solid';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Header from '../components/Header';
import Table from '../components/Table';

function PlanForm() {
    return (
        <div>
            <Head>
                <title>NetflixClone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/nficon2016.ico" />
            </Head>

            <header className="h-12 py-0 md:h-24 border-b border-b-gray-600 bg-[#181818]">
                <Link href="/" className="relative w-20 md:w-44 h-full">
                    <Image
                        alt="logo"
                        src="/Netflix-Brand-Logo.png"
                        className="object-cover"
                        fill
                    />
                </Link>
                <a className="text-medium md:text-xl font-medium hover:underline h-full flex items-center cursor-pointer">
                    Log out
                </a>
            </header>

            <main className="relative p-4 md:pl-4 pb-24 lg:space-y-14 lg:pl-20 mt-12 md:mt-24 max-w-5xl mx-auto">
                <div>
                    <h5>Step 1/2</h5>
                    <h2>Chọn gói dịch vụ phù hợp với bạn</h2>
                    <ul className="mt-4 space-y-4">
                        <li className="flex flex-row items-center space-x-2">
                            <CheckIcon className="w-9 h-9" color="#e50914" />
                            <span>
                                Truy cập thêm nhiều chương trình truyền hình và
                                phim.
                            </span>
                        </li>
                        <li className="flex flex-row items-center space-x-2">
                            <CheckIcon className="w-9 h-9" color="#e50914" />
                            <span>Lựa chọn xem trên nhiều thiết bị hơn.</span>
                        </li>
                        <li className="flex flex-row items-center space-x-2">
                            <CheckIcon className="w-9 h-9" color="#e50914" />
                            <span>
                                Thay đổi hoặc hủy gói dịch vụ của bạn bất cứ khi
                                nào.
                            </span>
                        </li>
                    </ul>
                </div>

                {/* Products */}
                <div className="flex flex-col md:flex-row justify-end">
                    <div className="flex flex-row mt-8 md:w-[60%]">
                        <div className="planBox">
                            <span className="text-center font-semibold">
                                Di Động
                            </span>
                        </div>
                        <div className="planBox">
                            <span className="text-center font-semibold">
                                Cơ bản
                            </span>
                        </div>
                        <div className="planBox">
                            <span className="text-center font-semibold">
                                Tiêu chuẩn
                            </span>
                        </div>
                        <div className="planBox">
                            <span className="text-center font-semibold">
                                Cao cấp
                            </span>
                        </div>
                    </div>
                </div>

                {/* Table */}
                <Table />
            </main>
        </div>
    );
}

export default PlanForm;
