import {
    ComputerDesktopIcon,
    DevicePhoneMobileIcon,
    DeviceTabletIcon,
    TvIcon,
} from '@heroicons/react/24/outline';
import { CheckIcon } from '@heroicons/react/24/solid';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import Table from '../components/Table';
import { Product } from '../typings';

const products: Product[] = [
    {
        id: 1,
        name: 'Di Động',
        price: 70000,
        currency: 'VND',
        quality: 'Tốt',
        resolution: '480p',
        devices: [
            {
                name: 'Điện thoại',
                icon: <DevicePhoneMobileIcon className="w-8 h-8" />,
            },
            {
                name: 'Máy tính bảng',
                icon: <DeviceTabletIcon className="w-8 h-8" />,
            },
        ],
    },
    {
        id: 2,
        name: 'Cơ bản',
        price: 180000,
        currency: 'VND',
        quality: 'Tốt',
        resolution: '720p',
        devices: [
            {
                name: 'Điện thoại',
                icon: <DevicePhoneMobileIcon className="w-8 h-8" />,
            },
            {
                name: 'Máy tính bảng',
                icon: <DeviceTabletIcon className="w-8 h-8" />,
            },
            {
                name: 'Máy tính',
                icon: <ComputerDesktopIcon className="w-8 h-8" />,
            },
            {
                name: 'TV',
                icon: <TvIcon className="w-8 h-8" />,
            },
        ],
    },
    {
        id: 3,
        name: 'Tiêu chuẩn',
        price: 220000,
        currency: 'VND',
        quality: 'Tốt hơn',
        resolution: '1080p',
        devices: [
            {
                name: 'Điện thoại',
                icon: <DevicePhoneMobileIcon className="w-8 h-8" />,
            },
            {
                name: 'Máy tính bảng',
                icon: <DeviceTabletIcon className="w-8 h-8" />,
            },
            {
                name: 'Máy tính',
                icon: <ComputerDesktopIcon className="w-8 h-8" />,
            },
            {
                name: 'TV',
                icon: <TvIcon className="w-8 h-8" />,
            },
        ],
    },
    {
        id: 4,
        name: 'Cao cấp',
        price: 260000,
        currency: 'VND',
        quality: 'Tốt nhất',
        resolution: '4K+HDR',
        devices: [
            {
                name: 'Điện thoại',
                icon: <DevicePhoneMobileIcon className="w-8 h-8" />,
            },
            {
                name: 'Máy tính bảng',
                icon: <DeviceTabletIcon className="w-8 h-8" />,
            },
            {
                name: 'Máy tính',
                icon: <ComputerDesktopIcon className="w-8 h-8" />,
            },
            {
                name: 'TV',
                icon: <TvIcon className="w-8 h-8" />,
            },
        ],
    },
];

function PlanForm() {
    const [selectProduct, setSelectProduct] = useState<Product | null>(null);
    return (
        <div>
            <Head>
                <title>NetflixClone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/nficon2016.ico" />
            </Head>

            <header className="h-12 py-0 md:h-24 border-b border-b-gray-600 bg-[#181818]">
                <Link href="/" className="relative w-20 md:w-44 h-full">
                    <Image
                        alt="logo"
                        src="/Netflix-Brand-Logo.png"
                        className="object-cover"
                        fill
                    />
                </Link>
                <a className="text-medium md:text-xl font-medium hover:underline h-full flex items-center cursor-pointer">
                    Log out
                </a>
            </header>

            <main className="relative p-4 md:pl-4 pb-24 lg:space-y-14 lg:pl-20 mt-12 md:mt-24 max-w-5xl mx-auto">
                <div className="mb-4">
                    <h5>Step 1/2</h5>
                    <h2>Chọn gói dịch vụ phù hợp với bạn</h2>
                    <ul className="mt-4 space-y-4">
                        <li className="flex flex-row items-center space-x-2">
                            <CheckIcon className="w-9 h-9" color="#e50914" />
                            <span>
                                Truy cập thêm nhiều chương trình truyền hình và
                                phim.
                            </span>
                        </li>
                        <li className="flex flex-row items-center space-x-2">
                            <CheckIcon className="w-9 h-9" color="#e50914" />
                            <span>Lựa chọn xem trên nhiều thiết bị hơn.</span>
                        </li>
                        <li className="flex flex-row items-center space-x-2">
                            <CheckIcon className="w-9 h-9" color="#e50914" />
                            <span>
                                Thay đổi hoặc hủy gói dịch vụ của bạn bất cứ khi
                                nào.
                            </span>
                        </li>
                    </ul>
                </div>

                {/* Products */}
                <div className="flex flex-col md:flex-row justify-end mb-4">
                    <div className="flex flex-row md:w-[60%]">
                        {products.map((product) => (
                            <div className="planBox" key={product.id}>
                                <span className="text-center font-semibold">
                                    {product.name}
                                </span>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Table */}
                <Table products={products} />

                <p className="text-gray-400 text-sm my-4">
                    Việc bạn có thể xem ở chế độ HD (720p), Full HD (1080p),
                    Ultra HD (4K) và HDR hay không phụ thuộc vào dịch vụ
                    internet và khả năng của thiết bị. Không phải tất cả nội
                    dung đều có sẵn ở mọi độ phân giải. Xem Điều khoản sử dụng
                    của chúng tôi để biết thêm chi tiết.
                </p>
                <p className="text-gray-400 text-sm mb-4">
                    Chỉ những người sống cùng bạn mới có thể dùng tài khoản của
                    bạn. Xem trên 4 thiết bị khác nhau cùng lúc với gói Cao cấp,
                    2 với gói Tiêu chuẩn và 1 với gói Cơ bản và Di động.
                </p>

                <div className="text-center">
                    <button className="w-full md:w-1/2 bg-primary px-10 py-5">
                        Tiếp theo
                    </button>
                </div>
            </main>
        </div>
    );
}

export default PlanForm;
